version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ="America/New_York"
      - PLEX_CLAIM=claim-GoRbtYstg3vUu3zHTGt8
    network_mode: host
    volumes:
      - /srv/plex/config:/config
      - /srv/plex/transcode:/transcode
      - /srv/plex/media:/data
