version: "2"
services:
  wetty:
    image: svenihoney/wetty
    container_name: wetty
    environment:
      - REMOTE_SSH_SERVER=elderberry.nstraub.com
      - REMOTE_SSH_PORT=22
      - REMOTE_SSH_USER=dylan
    ports:
      - 3000:3000
    restart: unless-stopped
